- name: Install eduroam Roaming Operator
  hosts: ro
  become: True
  vars_files:
    - group_vars/secrets.yml
  roles:
    - radsecproxy

  handlers:
    - name: restart radsecproxy
      service: name=radsecproxy state=restarted
