- name: Install eduroam Roaming Operator
  hosts: ro
  become: True
  vars_files:
    - group_vars/secrets.yml
  
  #Install Python2 on Ubuntu 16.04
  gather_facts: False
  pre_tasks:
    - raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    - setup: # aka gather_facts

  roles:
    - radsecproxy
    - { role: newrelic, when: play_newrelic == True }

  handlers:
    - name: restart radsecproxy
      service: name=radsecproxy state=restarted
    - name: restart rsyslog
      service: name=rsyslog state=restarted
