- name: Install eduroam Roaming Operator
  hosts: ro
  become: True
  vars_files:
    - group_vars/secrets.yml
  roles:
    - radsecproxy
    - { role: newrelic, when: play_newrelic == True }

  handlers:
    - name: restart radsecproxy
      service: name=radsecproxy state=restarted

    - name: restart rsyslog
      service: name=rsyslog state=restarted
